### PR TITLE
[rpcsx-os] sys_sysctl: use enum classes for names to better type safety

### PR DESCRIPTION
**Pull request by viniciuslrangel**
Just saying hello to the project while I read the source

### CODE REVIEW

**Comment by DHrpcs3** [comment]
Thank you for commit, but those enums are declared inside function, it is already best possible safety

**Comment by viniciuslrangel** [comment]
What about adding the sysctl name instead of unspec?

**Comment by DHrpcs3** [comment]
unspec is not random name, see sys___sysctl implementation in the FreeBSD

**Comment by viniciuslrangel** [comment]
https://github.com/freebsd/freebsd-src/blob/main/sys/sys/sysctl.h#L936

I can't find the unspec, it took me several minutes until I found the source and I was a little frustrated. It was what motivated me to do this commit

**Comment by DHrpcs3** [comment]
OS of PS4 is based on FreeBSD 9.1
https://github.com/freebsd/freebsd-src/blob/releng/9.1/sys/sys/sysctl.h#L421

**Comment by viniciuslrangel** [comment]
Oh, I actually forgot to check that. It makes a ton of sense. Thank you for clarifying

**Pull request closed without merging**
